# Generated by Django 4.2.7 on 2024-05-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_mails_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mails',
            options={'verbose_name': 'Почта', 'verbose_name_plural': 'Почта'},
        ),
    ]
