# Generated by Django 4.2.7 on 2024-05-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_mails_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
