# Generated by Django 4.2.7 on 2024-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_month_week_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписание занятий'},
        ),
        migrations.AlterField(
            model_name='class',
            name='train',
            field=models.CharField(max_length=128, verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=128, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='FIO',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=128, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Доп. запись'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.CharField(max_length=128, null=True, verbose_name='День недели'),
        ),
    ]
